/*
 * action types
 */

export const INIT_TICKETS = 'INIT_TICKETS'

export const SET_TICKETS = 'SET_TICKETS'

export const FILTER_BY_SPACE_ID = 'FILTER_BY_SPACE_ID'

export const FILTER_TICKETS_BY_STATUS = 'FILTER_TICKETS_BY_STATUS'

export const FILTER_TICKET_BY_DAYS_RANGE = 'FILTER_TICKET_BY_DAYS_RANGE'

export const SET_SPACES = 'SET_SPACES'

export const SELECT_SAPCE = 'SELECT_SPACE'

export const SELECT_TICKET = 'SELECT_TICKET'

export const RESOLVE_TICKET = 'RESOLVE_TICKET'

export const GET_FLOOR = 'GET_FLOOR'